# Site settings
title: Just Animate - Robust JavaScript animation library
description: > # this means to ignore newlines until "baseurl:"
  Just animate is a JavaScript animation library that plugs nicely into WAAPI
baseurl: "/just-animate-doc" # /just-animate-doc For temporary push to my fork
url: "https://josephrexme.github.io" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet

assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/img
    - _assets/js
    - _assets/scss
  cache: true
  cdn: https://josephrexme.github.io/
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json

timezone: America/Chicago
incremental: true
